### ISSUE TITLE
sdk 오류

### ISSUE THREAD

**Issue by yeonfish6040** [koreanbots/js-sdk#97]
오류 메시지 -
/home/discord/project/bloodmoon/node_modules/koreanbots/src/KoreanbotsClient.js:12
        this.options.koreanbotsOptions.interval = options.koreanbotsOptions.interval || 60000 * 30
                                                                            ^

TypeError: Cannot read property 'interval' of undefined
    at new KoreanbotsClient (/home/discord/project/bloodmoon/node_modules/koreanbots/src/KoreanbotsClient.js:12:77)
    at Object.<anonymous> (/home/discord/project/bloodmoon/bloodmoon.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

코드 -
const { KoreanbotsClient } = require("koreanbots");
const client = new KoreanbotsClient({
    intents: ["GUILDS", "GUILD_MESSAGES", "GUILD_MEMBERS", "DIRECT_MESSAGES"],
    koreanbots: {
        api: {
            token: "비밀"
        }
    },
    koreanbotsClient: {
        updateInterval: 600000 
    }
})

**Comment by zero734kr** [comment]
`yarn why koreanbots` 또는 `npm info koreanbots` 명령어를 실행한 스크린샷을 올려주세요.

**Comment by yeonfish6040** [comment]
![image](https://user-images.githubusercontent.com/72007187/132936994-bcb58eef-c8f2-4f38-9462-c4efeb9d870a.png)

**Comment by wonderlandpark** [comment]
혹시 package.json 첨부해주실 수 있나요?

**Comment by yeonfish6040** [comment]
![image](https://user-images.githubusercontent.com/72007187/132937857-df4c7c25-59b8-43cf-bffa-720240997acf.png)

**Comment by wonderlandpark** [comment]
모듈을 업데이트하지 않고 새로운 버전의 예시를 사용하셨습니다. 모듈을 `npm i koreanbots@latest` 로 업데이트 해주세요.

**Comment by yeonfish6040** [comment]
감사합니다!
